### ISSUE TITLE
Setting up the environment with -c anaconda instead of -c conda-forge

### ISSUE THREAD

**Issue by MartGro** [umarov90/DeepRAG#2]
I tried installing it in a new conda environment with `conda create -n ReFeaFi python=3.6`
When executing the following commands after activating, the relevant packages could not be found. 
```
conda install  conda-forge tensorflow-gpu==1.7.0
conda install cudatoolkit=9.0
conda install cudnn=7.1.2=cuda9.0_0
```

Instead, I tried
```
conda install -c anaconda tensorflow-gpu==1.7.0
conda install -c anaconda cudatoolkit=9.0
conda install -c anaconda cudnn=7.1.2=cuda9.0_0
```
This seems to work.

**Comment by ramzan1990** [comment]
Good, glad it worked.

**Comment by MartGro** [comment]
Hm, the example does not run :/
```
2022-02-10 17:14:28.246430: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 43038 MB memory) -> physical GPU (device: 0, name: NVIDIA A40, pci bus id: 0000:44:00.0, compute capability: 8.6)
Scanning chr20
2022-02-10 17:30:04.346877: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=128128, n=128, k=128
         [[Node: conv1d_3/conv1d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1d_1/conv1d/ExpandDims, conv1d_3/conv1d/ExpandDims_1)]]
         [[Node: output_prom/_1023 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1255_output_prom", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 304, in <module>
    main()
  File "predict.py", line 210, in main
    predict = sess.run(y, feed_dict={input_x: batch, kr: 1.0, in_training_mode: False})
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1140, in _run
    feed_dict_tensor, options, run_metadata)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    run_metadata)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=128128, n=128, k=128
         [[Node: conv1d_3/conv1d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1d_1/conv1d/ExpandDims, conv1d_3/conv1d/ExpandDims_1)]]
         [[Node: output_prom/_1023 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1255_output_prom", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'conv1d_3/conv1d/Conv2D', defined at:
  File "predict.py", line 304, in <module>
    main()
  File "predict.py", line 189, in main
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], models_folder + "model_scan")
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py", line 219, in load
    saver = tf_saver.import_meta_graph(meta_graph_def_to_load, **saver_kwargs)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1927, in import_meta_graph
    **kwargs)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 741, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 577, in import_graph_def
    op_def=op_def)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "home_dir/.conda/envs/ReFeaFi/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Blas SGEMM launch failed : m=128128, n=128, k=128
         [[Node: conv1d_3/conv1d/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv1d_1/conv1d/ExpandDims, conv1d_3/conv1d/ExpandDims_1)]]
         [[Node: output_prom/_1023 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1255_output_prom", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```


Do you think it has to do with the environment, or is it something else altogether?

**Comment by umarov90** [comment]
Can you try using 
conda install -c conda-forge tensorflow-gpu==1.7.0
instead of 
conda install  conda-forge tensorflow-gpu==1.7.0

**Comment by umarov90** [comment]
I just tested everything on Ubuntu 20.04 with conda version 4.10.3.
Please recreate the environment and run exactly the same commands as in Readme. 
If you still get "Blas SGEMM launch failed" error, according to stackoverflow questions, it is related to your GPU memory or drivers. Can you make sure that there is no other TensorFlow sessions running on your machine? You can also check using nvidia-smi command that the memory is free. Please try the solutions from here:
https://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed
